functions:
- startActivity:
    method: POST
    path: /activities
    proxy: null
    function: startActivity
- endActivity:
    method: PUT
    path: /activities/{+proxy}
    proxy: :id/end
    function: endActivity
- updateActivity:
    method: PUT
    path: /activities/update
    proxy: null
    function: updateActivity
- getActivity:
    method: GET
    path: /activities/details
    proxy: null
    function: getActivity
dynamodb:
  local:
    params:
      region: localhost
      endpoint: http://localhost:8005
    table: cvs-local-activities
    keys:
      - id
  remote:
    params: {}
    table: cvs-${BRANCH}-activities
serverless:
  basePath: /${BRANCH}
  port: 3007
